morse=[]
morse+=[". .-.. . -.-. - .-. --- -. .. -.-. ..."]
morse+=["..--- ----. ----. --... ----. ..--- ....- ..... ---.."]
morse+=["- .... . ....... --.- ..- .. -.-. -.- ....... -... .-. --- .-- -. ....... ..-. --- -..- ....... .--- ..- -- .--. ... ....... --- ...- . .-. ....... - .... . ....... .-.. .- --.. -.-- ....... -.. --- --."]
morse+=["..--- ---.. .-.-.- -.... .---- ...-- ----. ....... -. --..-- ....... --... --... .-.-.- ..--- ----- ----. ----- ....... ."]
# | dot               | 1    |
# | ----------------- | ---- |
# | symbol spacing    | 1    |
# | dash              | 3    |
# | character spacing | 3    |
# | word spacing      | 7    |
pulseDict={".":"HL","-":"HHHL"," ":"LL"}
result=[]
for i in range(len(morse)):
    pulse=""
    for ch in morse[i]:
        pulse+=pulseDict[ch]
    result+=[pulse]
print(result)
#['HLLLHLHHHLHLHLLLHLLLHHHLHLHHHLHLLLHHHLLLHLHHHLHLLLHHHLHHHLHHHLLLHHHLHLLLHLHLLLHHHLHLHHHLHLLLHLHLHL', 'HLHLHHHLHHHLHHHLLLHHHLHHHLHHHLHHHLHLLLHHHLHHHLHHHLHHHLHLLLHHHLHHHLHLHLHLLLHHHLHHHLHHHLHHHLHLLLHLHLHHHLHHHLHHHLLLHLHLHLHLHHHLLLHLHLHLHLHLLLHHHLHHHLHHHLHLHL', 'HHHLLLHLHLHLHLLLHLLLHLHLHLHLHLHLHLLLHHHLHHHLHLHHHLLLHLHLHHHLLLHLHLLLHHHLHLHHHLHLLLHHHLHLHHHLLLHLHLHLHLHLHLHLLLHHHLHLHLHLLLHLHHHLHLLLHHHLHHHLHHHLLLHLHHHLHHHLLLHHHLHLLLHLHLHLHLHLHLHLLLHLHLHHHLHLLLHHHLHHHLHHHLLLHHHLHLHLHHHLLLHLHLHLHLHLHLHLLLHLHHHLHHHLHHHLLLHLHLHHHLLLHHHLHHHLLLHLHHHLHHHLHLLLHLHLHLLLHLHLHLHLHLHLHLLLHHHLHHHLHHHLLLHLHLHLHHHLLLHLLLHLHHHLHLLLHLHLHLHLHLHLHLLLHHHLLLHLHLHLHLLLHLLLHLHLHLHLHLHLHLLLHLHHHLHLHLLLHLHHHLLLHHHLHHHLHLHLLLHHHLHLHHHLHHHLLLHLHLHLHLHLHLHLLLHHHLHLHLLLHHHLHHHLHHHLLLHHHLHHHLHL', 'HLHLHHHLHHHLHHHLLLHHHLHHHLHHHLHLHLLLHLHHHLHLHHHLHLHHHLLLHHHLHLHLHLHLLLHLHHHLHHHLHHHLHHHLLLHLHLHLHHHLHHHLLLHHHLHHHLHHHLHHHLHLLLHLHLHLHLHLHLHLLLHHHLHLLLHHHLHHHLHLHLHHHLHHHLLLHLHLHLHLHLHLHLLLHHHLHHHLHLHLHLLLHHHLHHHLHLHLHLLLHLHHHLHLHHHLHLHHHLLLHLHLHHHLHHHLHHHLLLHHHLHHHLHHHLHHHLHHHLLLHHHLHHHLHHHLHHHLHLLLHHHLHHHLHHHLHHHLHHHLLLHLHLHLHLHLHLHLLLHL']
